--- 
- hosts: ansible-db
  become: true
  tasks: 
   - name: Install tools
     apt: name={{item}} state=present update_cache=yes
     with_items:
         - python-mysqldb


   - name: install mysql-server
     apt: name=mysql-server state=present update_cache=yes
 
   - name: Ensure mysqls-server is started
     service: name=mysql state=started enabled=yes 

   - name: ensure mysql is runing on all ports
     lineinfile: dest=/etc/mysql/mariadb.conf.d/50-server.cnf regexp=^bind-address
                 line="bind-address = 0.0.0.0"
     notify: restart mysql

   - name: create demo database
     mysql_db: name=demo state=present

   - name: create demo user
     mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present 

  handlers:
   - name: restart mysql
     service: name=mysql state=restarted

