---
- hosts: ansible-webserver
  become: true
  tasks: 
    - name: verify webserver
      command: service apache2 status

    - name: verify if apache is runnig on port 80
      wait_for: port=80 timeout=10

- hosts: ansible-lb
  become: true
  tasks:
    - name: verify nginx
      command: service nginx status

    - name: verify if nginx is running on port 80
      wait_for: port=80 timeout=10

- hosts: ansible-db
  become: true
  tasks:
    - name: verify DB 
      command: service mysql status

    - name: verify if mysql is running on 3306
      wait_for: port=3306 timeout=10




