--- 
- hosts: ansible-webserver
  become: true
  tasks:
    - name: install apache2 using with_item module- all web components 
      apt: name={{item}} state=present update_cache=yes
      with_items:
         - apache2
         - libapache2-mod-wsgi
         - python-pip
         - python-virtualenv

    - name: Ensure apache2 is started
      service: name=apache2 state=started enabled=yes 
